name: 'Delombok.'
description: 'Delombok the given directory'
inputs:
  directory:
    description: 'Path to the directory to delombok'
    required: false
    default: ${{ github.workspace }}
runs:
  using: "composite"
  steps:
    # Make sure Python is install
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - run: ${{ github.action_path }}/delombok.sh "${{ inputs.directory }}"
      shell: bash
